minecraftMappingChannel=parchment
minecraftMappingVersion=2024.11.17-1.21.1

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
# Environment Properties
# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
# The Minecraft version must agree with the Neo version to get a valid artifact
minecraftVersion=1.21.1
# The Minecraft version range can use any release version of Minecraft as bounds.
# Snapshots, pre-releases, and release candidates are not guaranteed to sort properly
# as they do not follow standard versioning conventions.
minecraftVersionRange=[1.21.1]
# The Neo version must agree with the Minecraft version to get a valid artifact
neo_version=21.1.215
# The loader version range can only use the major version of FML as bounds
modLoader=kotlinforforge
kotlinForForgeVersion=5.10.0
kotlinForForgeVersionRange=[5.4,)
modLoaderVersionRange=[5.4,)
